//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ultimus.UWF.Form.ProcessControl.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ultimus.UWF.Form.ProcessControl.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Approval History 的本地化字符串。
        /// </summary>
        public static string ApprovalHistory {
            get {
                return ResourceManager.GetString("ApprovalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approve 的本地化字符串。
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approve Action 的本地化字符串。
        /// </summary>
        public static string ApproveAction {
            get {
                return ResourceManager.GetString("ApproveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select approve action! 的本地化字符串。
        /// </summary>
        public static string ApproveActionRequire {
            get {
                return ResourceManager.GetString("ApproveActionRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string ApproveDate {
            get {
                return ResourceManager.GetString("ApproveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approver Name 的本地化字符串。
        /// </summary>
        public static string Approver {
            get {
                return ResourceManager.GetString("Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        public static string ApproveResult {
            get {
                return ResourceManager.GetString("ApproveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 咨询人 Inquire 的本地化字符串。
        /// </summary>
        public static string AskFor {
            get {
                return ResourceManager.GetString("AskFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attachment Information 的本地化字符串。
        /// </summary>
        public static string AttachmentInfo {
            get {
                return ResourceManager.GetString("AttachmentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attachment required! 的本地化字符串。
        /// </summary>
        public static string AttachmentRequire {
            get {
                return ResourceManager.GetString("AttachmentRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 char 的本地化字符串。
        /// </summary>
        public static string Char {
            get {
                return ResourceManager.GetString("Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approve Comments 的本地化字符串。
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not submit, the char length must less than 4000! 的本地化字符串。
        /// </summary>
        public static string CommentsOverLength {
            get {
                return ResourceManager.GetString("CommentsOverLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create By 的本地化字符串。
        /// </summary>
        public static string CreateBy {
            get {
                return ResourceManager.GetString("CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Draft 的本地化字符串。
        /// </summary>
        public static string DraftSave {
            get {
                return ResourceManager.GetString("DraftSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileName 的本地化字符串。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Have attachment has not upload, do you want to submit? 的本地化字符串。
        /// </summary>
        public static string HaveFile {
            get {
                return ResourceManager.GetString("HaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max lenght is 1000 char , now input 的本地化字符串。
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input details! 的本地化字符串。
        /// </summary>
        public static string MustInputDetail {
            get {
                return ResourceManager.GetString("MustInputDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewRequest 的本地化字符串。
        /// </summary>
        public static string NewRequest {
            get {
                return ResourceManager.GetString("NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comments Required! 的本地化字符串。
        /// </summary>
        public static string RequireComments {
            get {
                return ResourceManager.GetString("RequireComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please upload attachment! 的本地化字符串。
        /// </summary>
        public static string RequireUpload {
            get {
                return ResourceManager.GetString("RequireUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Draft 的本地化字符串。
        /// </summary>
        public static string SaveDraft {
            get {
                return ResourceManager.GetString("SaveDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Success! 的本地化字符串。
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StepName 的本地化字符串。
        /// </summary>
        public static string StepName {
            get {
                return ResourceManager.GetString("StepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to submit? 的本地化字符串。
        /// </summary>
        public static string SubmitConfirm {
            get {
                return ResourceManager.GetString("SubmitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submiting... 的本地化字符串。
        /// </summary>
        public static string Submiting {
            get {
                return ResourceManager.GetString("Submiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit Success! 的本地化字符串。
        /// </summary>
        public static string SubmitSuccess {
            get {
                return ResourceManager.GetString("SubmitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 test 的本地化字符串。
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload 的本地化字符串。
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
    }
}
