
CREATE TABLE [dbo].[WF_TASKQUEUE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TASKID] [nvarchar](50) NULL,
	[LOGINNAME] [nvarchar](50) NULL,
	[SYNC] [char](1) NULL,
	[SUMMARY] [nvarchar](200) NULL,
	[REASON] [nvarchar](200) NULL,
	[COMMENTS] [nvarchar](400) NULL,
	[PROCESSNAME] [nvarchar](100) NULL,
	[INCIDENT] [int] NULL,
	[STEPNAME] [nvarchar](100) NULL,
	[ERRORMESSAGE] [nvarchar](400) NULL,
	[VARLIST] [xml] NULL,
	[ACTION] [nvarchar](50) NULL,
	[STATUS] [int] NULL,
	[RETRYTIME] [int] NULL,
	[CREATEDATE] [datetime] NULL,
	[SUBMITDATE] [datetime] NULL,
 CONSTRAINT [PK_WF_TASKQUEUE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO