//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ultimus.UWF.Home2.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_cn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_cn() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ultimus.UWF.Home2.Resources.zh_cn", typeof(zh_cn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/V2/barner-zh.png 的本地化字符串。
        /// </summary>
        internal static string Barner {
            get {
                return ResourceManager.GetString("Barner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/V2/ccbx-zh.png 的本地化字符串。
        /// </summary>
        internal static string Btn_Create_CCBX {
            get {
                return ResourceManager.GetString("Btn_Create_CCBX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/V2/ccsq-zh.png 的本地化字符串。
        /// </summary>
        internal static string Btn_Create_CCSQ {
            get {
                return ResourceManager.GetString("Btn_Create_CCSQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/V2/grbt-zh.png 的本地化字符串。
        /// </summary>
        internal static string Btn_Create_GRBT {
            get {
                return ResourceManager.GetString("Btn_Create_GRBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/V2/grbx-zh.png 的本地化字符串。
        /// </summary>
        internal static string Btn_Create_GRBX {
            get {
                return ResourceManager.GetString("Btn_Create_GRBX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/V2/xjyz-zh.png 的本地化字符串。
        /// </summary>
        internal static string Btn_Create_XJYZ {
            get {
                return ResourceManager.GetString("Btn_Create_XJYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/V2/search-zh.png 的本地化字符串。
        /// </summary>
        internal static string Btn_Toolbar_Search {
            get {
                return ResourceManager.GetString("Btn_Toolbar_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong UserName Or Password! 的本地化字符串。
        /// </summary>
        internal static string CheckUserInfoFail {
            get {
                return ResourceManager.GetString("CheckUserInfoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserName Or Password can&quot;\&apos;&quot;t be null 的本地化字符串。
        /// </summary>
        internal static string CheckUserInfoNull {
            get {
                return ResourceManager.GetString("CheckUserInfoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --Select-- 的本地化字符串。
        /// </summary>
        internal static string DropdownListItemEmpty {
            get {
                return ResourceManager.GetString("DropdownListItemEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出差报销 的本地化字符串。
        /// </summary>
        internal static string FlowName_CCBX {
            get {
                return ResourceManager.GetString("FlowName_CCBX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出差申请 的本地化字符串。
        /// </summary>
        internal static string FlowName_CCSQ {
            get {
                return ResourceManager.GetString("FlowName_CCSQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人补贴 的本地化字符串。
        /// </summary>
        internal static string FlowName_GRBT {
            get {
                return ResourceManager.GetString("FlowName_GRBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人报销 的本地化字符串。
        /// </summary>
        internal static string FlowName_GRBX {
            get {
                return ResourceManager.GetString("FlowName_GRBX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现金预支 的本地化字符串。
        /// </summary>
        internal static string FlowName_XJYZ {
            get {
                return ResourceManager.GetString("FlowName_XJYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No records! 的本地化字符串。
        /// </summary>
        internal static string Grid_EmptyData_Text {
            get {
                return ResourceManager.GetString("Grid_EmptyData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-cn 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drafts 的本地化字符串。
        /// </summary>
        internal static string Menu_CGX {
            get {
                return ResourceManager.GetString("Menu_CGX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        internal static string Menu_CJLC {
            get {
                return ResourceManager.GetString("Menu_CJLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Todo 的本地化字符串。
        /// </summary>
        internal static string Menu_DBRW {
            get {
                return ResourceManager.GetString("Menu_DBRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Request 的本地化字符串。
        /// </summary>
        internal static string Menu_WDSQ {
            get {
                return ResourceManager.GetString("Menu_WDSQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        internal static string Menu_YBRW {
            get {
                return ResourceManager.GetString("Menu_YBRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sender 的本地化字符串。
        /// </summary>
        internal static string Text_GridHeader_CurrentBy {
            get {
                return ResourceManager.GetString("Text_GridHeader_CurrentBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step 的本地化字符串。
        /// </summary>
        internal static string Text_GridHeader_CurrentStep {
            get {
                return ResourceManager.GetString("Text_GridHeader_CurrentStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow 的本地化字符串。
        /// </summary>
        internal static string Text_GridHeader_Flow {
            get {
                return ResourceManager.GetString("Text_GridHeader_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string Text_GridHeader_No {
            get {
                return ResourceManager.GetString("Text_GridHeader_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RequestNo 的本地化字符串。
        /// </summary>
        internal static string Text_GridHeader_RequestNo {
            get {
                return ResourceManager.GetString("Text_GridHeader_RequestNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        internal static string Text_GridHeader_SendBy {
            get {
                return ResourceManager.GetString("Text_GridHeader_SendBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        internal static string Text_GridHeader_SendDate {
            get {
                return ResourceManager.GetString("Text_GridHeader_SendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step 的本地化字符串。
        /// </summary>
        internal static string Text_GridHeader_Step {
            get {
                return ResourceManager.GetString("Text_GridHeader_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        internal static string Text_GridHeader_Title {
            get {
                return ResourceManager.GetString("Text_GridHeader_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        internal static string Text_ToolBar_Date {
            get {
                return ResourceManager.GetString("Text_ToolBar_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Text_ToolBar_Del {
            get {
                return ResourceManager.GetString("Text_ToolBar_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string Text_ToolBar_Flow {
            get {
                return ResourceManager.GetString("Text_ToolBar_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor 的本地化字符串。
        /// </summary>
        internal static string Text_ToolBar_Monitor {
            get {
                return ResourceManager.GetString("Text_ToolBar_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title/No. 的本地化字符串。
        /// </summary>
        internal static string Text_ToolBar_Title {
            get {
                return ResourceManager.GetString("Text_ToolBar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change User 的本地化字符串。
        /// </summary>
        internal static string UserAccountChange {
            get {
                return ResourceManager.GetString("UserAccountChange", resourceCulture);
            }
        }
    }
}
