//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Loading already do task list error 的本地化字符串。
        /// </summary>
        internal static string AlreadyDoTask_ErrorMessage1 {
            get {
                return ResourceManager.GetString("AlreadyDoTask_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter process name 的本地化字符串。
        /// </summary>
        internal static string AlreadyDoTask_ProcessName {
            get {
                return ResourceManager.GetString("AlreadyDoTask_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First    的本地化字符串。
        /// </summary>
        internal static string AspNetPager_FirstPageText {
            get {
                return ResourceManager.GetString("AspNetPager_FirstPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First    的本地化字符串。
        /// </summary>
        internal static string AspNetPager_FirstPageText1 {
            get {
                return ResourceManager.GetString("AspNetPager_FirstPageText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 的本地化字符串。
        /// </summary>
        internal static string AspNetPager_LastPageText {
            get {
                return ResourceManager.GetString("AspNetPager_LastPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 的本地化字符串。
        /// </summary>
        internal static string AspNetPager_LastPageText1 {
            get {
                return ResourceManager.GetString("AspNetPager_LastPageText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    Next    的本地化字符串。
        /// </summary>
        internal static string AspNetPager_NextPageText {
            get {
                return ResourceManager.GetString("AspNetPager_NextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    Next    的本地化字符串。
        /// </summary>
        internal static string AspNetPager_NextPageText1 {
            get {
                return ResourceManager.GetString("AspNetPager_NextPageText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prev    的本地化字符串。
        /// </summary>
        internal static string AspNetPager_PrevPageText {
            get {
                return ResourceManager.GetString("AspNetPager_PrevPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prev    的本地化字符串。
        /// </summary>
        internal static string AspNetPager_PrevPageText1 {
            get {
                return ResourceManager.GetString("AspNetPager_PrevPageText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Name 的本地化字符串。
        /// </summary>
        internal static string ControlSourceConfig_ColumnName {
            get {
                return ResourceManager.GetString("ControlSourceConfig_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data source type 的本地化字符串。
        /// </summary>
        internal static string ControlSourceConfig_ControlSourceType {
            get {
                return ResourceManager.GetString("ControlSourceConfig_ControlSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field Name 的本地化字符串。
        /// </summary>
        internal static string ControlSourceConfig_ControlSource_ColumnName {
            get {
                return ResourceManager.GetString("ControlSourceConfig_ControlSource_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConnectionString 的本地化字符串。
        /// </summary>
        internal static string ControlSourceConfig_ControlSource_ConnectionString {
            get {
                return ResourceManager.GetString("ControlSourceConfig_ControlSource_ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataBase 的本地化字符串。
        /// </summary>
        internal static string ControlSourceConfig_ControlSource_DataBase {
            get {
                return ResourceManager.GetString("ControlSourceConfig_ControlSource_DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ElectronicForm 的本地化字符串。
        /// </summary>
        internal static string ControlSourceConfig_ControlSource_ElectronicForm {
            get {
                return ResourceManager.GetString("ControlSourceConfig_ControlSource_ElectronicForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Where 的本地化字符串。
        /// </summary>
        internal static string ControlSourceConfig_ControlSource_strWhere {
            get {
                return ResourceManager.GetString("ControlSourceConfig_ControlSource_strWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TableName 的本地化字符串。
        /// </summary>
        internal static string ControlSourceConfig_ControlSource_TableName {
            get {
                return ResourceManager.GetString("ControlSourceConfig_ControlSource_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable Name 的本地化字符串。
        /// </summary>
        internal static string ControlSourceConfig_ControlSource_VariableName {
            get {
                return ResourceManager.GetString("ControlSourceConfig_ControlSource_VariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading data error 的本地化字符串。
        /// </summary>
        internal static string ControlSourceConfig_ErrorMessage1 {
            get {
                return ResourceManager.GetString("ControlSourceConfig_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data save error 的本地化字符串。
        /// </summary>
        internal static string ControlSourceConfig_ErrorMessage2 {
            get {
                return ResourceManager.GetString("ControlSourceConfig_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Name 的本地化字符串。
        /// </summary>
        internal static string ControlSourceConfig_ProcessName {
            get {
                return ResourceManager.GetString("ControlSourceConfig_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Name 的本地化字符串。
        /// </summary>
        internal static string ControlSourceConfig_StepName {
            get {
                return ResourceManager.GetString("ControlSourceConfig_StepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Name 的本地化字符串。
        /// </summary>
        internal static string DataSaveConfig_ColumnName {
            get {
                return ResourceManager.GetString("DataSaveConfig_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection String 的本地化字符串。
        /// </summary>
        internal static string DataSaveConfig_ConnectionString {
            get {
                return ResourceManager.GetString("DataSaveConfig_ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save to database 的本地化字符串。
        /// </summary>
        internal static string DataSaveConfig_DataBase {
            get {
                return ResourceManager.GetString("DataSaveConfig_DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save to electronic form 的本地化字符串。
        /// </summary>
        internal static string DataSaveConfig_ElectronicForm {
            get {
                return ResourceManager.GetString("DataSaveConfig_ElectronicForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field Name 的本地化字符串。
        /// </summary>
        internal static string DataSaveConfig_FieldName {
            get {
                return ResourceManager.GetString("DataSaveConfig_FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Master 的本地化字符串。
        /// </summary>
        internal static string DataSaveConfig_IsMaster {
            get {
                return ResourceManager.GetString("DataSaveConfig_IsMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Sublist 的本地化字符串。
        /// </summary>
        internal static string DataSaveConfig_IsSublist {
            get {
                return ResourceManager.GetString("DataSaveConfig_IsSublist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master Table Config 的本地化字符串。
        /// </summary>
        internal static string DataSaveConfig_MasterConfig {
            get {
                return ResourceManager.GetString("DataSaveConfig_MasterConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string DataSaveConfig_No {
            get {
                return ResourceManager.GetString("DataSaveConfig_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Name 的本地化字符串。
        /// </summary>
        internal static string DataSaveConfig_ProcessName {
            get {
                return ResourceManager.GetString("DataSaveConfig_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Name 的本地化字符串。
        /// </summary>
        internal static string DataSaveConfig_StepName {
            get {
                return ResourceManager.GetString("DataSaveConfig_StepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sublist Table Config 的本地化字符串。
        /// </summary>
        internal static string DataSaveConfig_SublistConfig {
            get {
                return ResourceManager.GetString("DataSaveConfig_SublistConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Name 的本地化字符串。
        /// </summary>
        internal static string DataSaveConfig_TableName {
            get {
                return ResourceManager.GetString("DataSaveConfig_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable Name 的本地化字符串。
        /// </summary>
        internal static string DataSaveConfig_VariableName {
            get {
                return ResourceManager.GetString("DataSaveConfig_VariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Page 的本地化字符串。
        /// </summary>
        internal static string Default_CreatePage {
            get {
                return ResourceManager.GetString("Default_CreatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration/Modify 的本地化字符串。
        /// </summary>
        internal static string Default_List_ConfigurationOrModify {
            get {
                return ResourceManager.GetString("Default_List_ConfigurationOrModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Page 的本地化字符串。
        /// </summary>
        internal static string Default_List_CreatePage {
            get {
                return ResourceManager.GetString("Default_List_CreatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Time 的本地化字符串。
        /// </summary>
        internal static string Default_List_CreateTime {
            get {
                return ResourceManager.GetString("Default_List_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading list information error 的本地化字符串。
        /// </summary>
        internal static string Default_List_ErrorMessage1 {
            get {
                return ResourceManager.GetString("Default_List_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string Default_List_No {
            get {
                return ResourceManager.GetString("Default_List_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        internal static string Default_List_Operation {
            get {
                return ResourceManager.GetString("Default_List_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Name 的本地化字符串。
        /// </summary>
        internal static string Default_List_ProcessName {
            get {
                return ResourceManager.GetString("Default_List_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Time 的本地化字符串。
        /// </summary>
        internal static string Default_List_UpdateTime {
            get {
                return ResourceManager.GetString("Default_List_UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Create Page 的本地化字符串。
        /// </summary>
        internal static string Default_Search_CreatePage {
            get {
                return ResourceManager.GetString("Default_Search_CreatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Time 的本地化字符串。
        /// </summary>
        internal static string Default_Search_CreateTime {
            get {
                return ResourceManager.GetString("Default_Search_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Name 的本地化字符串。
        /// </summary>
        internal static string Default_Search_ProcessName {
            get {
                return ResourceManager.GetString("Default_Search_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string Default_Search_ResetButton {
            get {
                return ResourceManager.GetString("Default_Search_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string Default_Search_SearchButton {
            get {
                return ResourceManager.GetString("Default_Search_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Time 的本地化字符串。
        /// </summary>
        internal static string Default_Search_UpdateTime {
            get {
                return ResourceManager.GetString("Default_Search_UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Row 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_AddButton {
            get {
                return ResourceManager.GetString("FormConfiguration_List_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_Choose {
            get {
                return ResourceManager.GetString("FormConfiguration_List_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Name 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_ColumnName {
            get {
                return ResourceManager.GetString("FormConfiguration_List_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_Configure {
            get {
                return ResourceManager.GetString("FormConfiguration_List_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Source 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_ConfigureDataSource {
            get {
                return ResourceManager.GetString("FormConfiguration_List_ConfigureDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control Name 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_ControlName {
            get {
                return ResourceManager.GetString("FormConfiguration_List_ControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value Format 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_ControlValueFormat {
            get {
                return ResourceManager.GetString("FormConfiguration_List_ControlValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete rows 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_DelButton {
            get {
                return ResourceManager.GetString("FormConfiguration_List_DelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading list information error 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_ErrorMessage1 {
            get {
                return ResourceManager.GetString("FormConfiguration_List_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add line error 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_ErrorMessage2 {
            get {
                return ResourceManager.GetString("FormConfiguration_List_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete rows error 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_ErrorMessage3 {
            get {
                return ResourceManager.GetString("FormConfiguration_List_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading control list error 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_ErrorMessage4 {
            get {
                return ResourceManager.GetString("FormConfiguration_List_ErrorMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save data error 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_ErrorMessage5 {
            get {
                return ResourceManager.GetString("FormConfiguration_List_ErrorMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External Link 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_ExternalLinks {
            get {
                return ResourceManager.GetString("FormConfiguration_List_ExternalLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save and return 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_GoBackButton {
            get {
                return ResourceManager.GetString("FormConfiguration_List_GoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Show 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_IsShow {
            get {
                return ResourceManager.GetString("FormConfiguration_List_IsShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_No {
            get {
                return ResourceManager.GetString("FormConfiguration_List_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order By 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_OrderBy {
            get {
                return ResourceManager.GetString("FormConfiguration_List_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Name 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_ProcessName {
            get {
                return ResourceManager.GetString("FormConfiguration_List_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReadOnly 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_ReadOnly {
            get {
                return ResourceManager.GetString("FormConfiguration_List_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_Required {
            get {
                return ResourceManager.GetString("FormConfiguration_List_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Name 的本地化字符串。
        /// </summary>
        internal static string FormConfiguration_List_StepName {
            get {
                return ResourceManager.GetString("FormConfiguration_List_StepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approval History 的本地化字符串。
        /// </summary>
        internal static string Form_ApprovalHistory {
            get {
                return ResourceManager.GetString("Form_ApprovalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow Chart 的本地化字符串。
        /// </summary>
        internal static string Form_FlowChart {
            get {
                return ResourceManager.GetString("Form_FlowChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form 的本地化字符串。
        /// </summary>
        internal static string Form_Text {
            get {
                return ResourceManager.GetString("Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Off 的本地化字符串。
        /// </summary>
        internal static string HeaderLogOff {
            get {
                return ResourceManager.GetString("HeaderLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Languages 的本地化字符串。
        /// </summary>
        internal static string LoginLanguages {
            get {
                return ResourceManager.GetString("LoginLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string LoginLanguages_EN {
            get {
                return ResourceManager.GetString("LoginLanguages_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        internal static string LoginLanguages_ZH {
            get {
                return ResourceManager.GetString("LoginLanguages_ZH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domain 的本地化字符串。
        /// </summary>
        internal static string Login_Domain {
            get {
                return ResourceManager.GetString("Login_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get domain information error 的本地化字符串。
        /// </summary>
        internal static string Login_ErrorMessage1 {
            get {
                return ResourceManager.GetString("Login_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Landing error 的本地化字符串。
        /// </summary>
        internal static string Login_ErrorMessage2 {
            get {
                return ResourceManager.GetString("Login_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name or password mistake, please enter again 的本地化字符串。
        /// </summary>
        internal static string Login_ErrorMessage3 {
            get {
                return ResourceManager.GetString("Login_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pass Word 的本地化字符串。
        /// </summary>
        internal static string Login_PassWord {
            get {
                return ResourceManager.GetString("Login_PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        internal static string Login_UserName {
            get {
                return ResourceManager.GetString("Login_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading process number error 的本地化字符串。
        /// </summary>
        internal static string NewTaskList_ErrorMessage1 {
            get {
                return ResourceManager.GetString("NewTaskList_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error loading process information 的本地化字符串。
        /// </summary>
        internal static string NewTaskList_ErrorMessage2 {
            get {
                return ResourceManager.GetString("NewTaskList_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click on the specific process for launch 的本地化字符串。
        /// </summary>
        internal static string NewTaskList_Remark1 {
            get {
                return ResourceManager.GetString("NewTaskList_Remark1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contains process under 的本地化字符串。
        /// </summary>
        internal static string NewTaskList_Remark2 {
            get {
                return ResourceManager.GetString("NewTaskList_Remark2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 number 的本地化字符串。
        /// </summary>
        internal static string NewTaskList_Remark3 {
            get {
                return ResourceManager.GetString("NewTaskList_Remark3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already Do Task 的本地化字符串。
        /// </summary>
        internal static string NewTask_AlreadyDoTask {
            get {
                return ResourceManager.GetString("NewTask_AlreadyDoTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading classification error 的本地化字符串。
        /// </summary>
        internal static string NewTask_ErrorMessage1 {
            get {
                return ResourceManager.GetString("NewTask_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch Process 的本地化字符串。
        /// </summary>
        internal static string NewTask_NewTask {
            get {
                return ResourceManager.GetString("NewTask_NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To-Do Tasks 的本地化字符串。
        /// </summary>
        internal static string NewTask_ToDoTask {
            get {
                return ResourceManager.GetString("NewTask_ToDoTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please upload 的本地化字符串。
        /// </summary>
        internal static string ProcessConfig_CheckFileMessage1 {
            get {
                return ResourceManager.GetString("ProcessConfig_CheckFileMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type of document 的本地化字符串。
        /// </summary>
        internal static string ProcessConfig_CheckFileMessage2 {
            get {
                return ResourceManager.GetString("ProcessConfig_CheckFileMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config Step 的本地化字符串。
        /// </summary>
        internal static string ProcessConfig_ConfigStep {
            get {
                return ResourceManager.GetString("ProcessConfig_ConfigStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading data error 的本地化字符串。
        /// </summary>
        internal static string ProcessConfig_ErrorMessage1 {
            get {
                return ResourceManager.GetString("ProcessConfig_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page Logo 的本地化字符串。
        /// </summary>
        internal static string ProcessConfig_LoGo {
            get {
                return ResourceManager.GetString("ProcessConfig_LoGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload/update 的本地化字符串。
        /// </summary>
        internal static string ProcessConfig_UpLoadButton {
            get {
                return ResourceManager.GetString("ProcessConfig_UpLoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload file error 的本地化字符串。
        /// </summary>
        internal static string ProcessConfig_UpLoadErrorMessage1 {
            get {
                return ResourceManager.GetString("ProcessConfig_UpLoadErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Image 的本地化字符串。
        /// </summary>
        internal static string ProcessConfig_ViewImage {
            get {
                return ResourceManager.GetString("ProcessConfig_ViewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading process monitoring diagram error 的本地化字符串。
        /// </summary>
        internal static string ProcessMonitoring_ErrorMessage1 {
            get {
                return ResourceManager.GetString("ProcessMonitoring_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approval Configuration 的本地化字符串。
        /// </summary>
        internal static string ProcessStepList_List_ApprovalConfiguration {
            get {
                return ResourceManager.GetString("ProcessStepList_List_ApprovalConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify/configuration 的本地化字符串。
        /// </summary>
        internal static string ProcessStepList_List_ApprovalOperation {
            get {
                return ResourceManager.GetString("ProcessStepList_List_ApprovalOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy to other steps 的本地化字符串。
        /// </summary>
        internal static string ProcessStepList_List_Copy {
            get {
                return ResourceManager.GetString("ProcessStepList_List_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Save 的本地化字符串。
        /// </summary>
        internal static string ProcessStepList_List_DataSave {
            get {
                return ResourceManager.GetString("ProcessStepList_List_DataSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 configuration/modify 的本地化字符串。
        /// </summary>
        internal static string ProcessStepList_List_DataSaveConfig {
            get {
                return ResourceManager.GetString("ProcessStepList_List_DataSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data save error 的本地化字符串。
        /// </summary>
        internal static string ProcessStepList_List_ErrorMessage1 {
            get {
                return ResourceManager.GetString("ProcessStepList_List_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading list error 的本地化字符串。
        /// </summary>
        internal static string ProcessStepList_List_ErrorMessage2 {
            get {
                return ResourceManager.GetString("ProcessStepList_List_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading {0} data error 的本地化字符串。
        /// </summary>
        internal static string ProcessStepList_List_ErrorMessage3 {
            get {
                return ResourceManager.GetString("ProcessStepList_List_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form Configuration 的本地化字符串。
        /// </summary>
        internal static string ProcessStepList_List_FormConfiguration {
            get {
                return ResourceManager.GetString("ProcessStepList_List_FormConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify/configuration 的本地化字符串。
        /// </summary>
        internal static string ProcessStepList_List_FormOperation {
            get {
                return ResourceManager.GetString("ProcessStepList_List_FormOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string ProcessStepList_List_No {
            get {
                return ResourceManager.GetString("ProcessStepList_List_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Name 的本地化字符串。
        /// </summary>
        internal static string ProcessStepList_List_ProcessName {
            get {
                return ResourceManager.GetString("ProcessStepList_List_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shortcuts 的本地化字符串。
        /// </summary>
        internal static string ProcessStepList_List_Shortcuts {
            get {
                return ResourceManager.GetString("ProcessStepList_List_Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Name (Chinese) 的本地化字符串。
        /// </summary>
        internal static string ProcessStepList_List_StepCName {
            get {
                return ResourceManager.GetString("ProcessStepList_List_StepCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Name (English) 的本地化字符串。
        /// </summary>
        internal static string ProcessStepList_List_StepEName {
            get {
                return ResourceManager.GetString("ProcessStepList_List_StepEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Name 的本地化字符串。
        /// </summary>
        internal static string ProcessStepList_List_StepName {
            get {
                return ResourceManager.GetString("ProcessStepList_List_StepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string StepConfigCopy_Confirm {
            get {
                return ResourceManager.GetString("StepConfigCopy_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        internal static string StepConfigCopy_Return {
            get {
                return ResourceManager.GetString("StepConfigCopy_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading pending task list error 的本地化字符串。
        /// </summary>
        internal static string ToDoTask_ErrorMessage1 {
            get {
                return ResourceManager.GetString("ToDoTask_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incident 的本地化字符串。
        /// </summary>
        internal static string ToDoTask_Incident {
            get {
                return ResourceManager.GetString("ToDoTask_Incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Form 的本地化字符串。
        /// </summary>
        internal static string ToDoTask_OpenForm {
            get {
                return ResourceManager.GetString("ToDoTask_OpenForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitoring 的本地化字符串。
        /// </summary>
        internal static string ToDoTask_ProcessMonitoring {
            get {
                return ResourceManager.GetString("ToDoTask_ProcessMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Name 的本地化字符串。
        /// </summary>
        internal static string ToDoTask_ProcessName {
            get {
                return ResourceManager.GetString("ToDoTask_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Name 的本地化字符串。
        /// </summary>
        internal static string ToDoTask_StepName {
            get {
                return ResourceManager.GetString("ToDoTask_StepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Summary 的本地化字符串。
        /// </summary>
        internal static string ToDoTask_Summary {
            get {
                return ResourceManager.GetString("ToDoTask_Summary", resourceCulture);
            }
        }
    }
}
