//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Ultimus.UWF.Workflow.EmailServices.ProcessAPI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EIKServiceSoap", Namespace="http://tempuri.org/")]
    public partial class EIKService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetInitProcessListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyTaskListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyRequestListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyApprovalListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitTaskOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateTaskOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveApprovalHistroyOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReturnTaskOperationCompleted;
        
        private System.Threading.SendOrPostCallback RejectTaskOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTaskInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGraphicalStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVariableListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVariableXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInitialVariableOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInitTaskIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDomainsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserEntityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfoBySearchTextOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInquireListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EIKService() {
            this.Url = global::Ultimus.UWF.Workflow.EmailServices.Properties.Settings.Default.Ultimus_UWF_Workflow_EmailServices_ProcessAPI_EIKService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetInitProcessListCompletedEventHandler GetInitProcessListCompleted;
        
        /// <remarks/>
        public event GetMyTaskListCompletedEventHandler GetMyTaskListCompleted;
        
        /// <remarks/>
        public event GetMyRequestListCompletedEventHandler GetMyRequestListCompleted;
        
        /// <remarks/>
        public event GetMyApprovalListCompletedEventHandler GetMyApprovalListCompleted;
        
        /// <remarks/>
        public event SubmitTaskCompletedEventHandler SubmitTaskCompleted;
        
        /// <remarks/>
        public event CreateTaskCompletedEventHandler CreateTaskCompleted;
        
        /// <remarks/>
        public event SaveApprovalHistroyCompletedEventHandler SaveApprovalHistroyCompleted;
        
        /// <remarks/>
        public event ReturnTaskCompletedEventHandler ReturnTaskCompleted;
        
        /// <remarks/>
        public event RejectTaskCompletedEventHandler RejectTaskCompleted;
        
        /// <remarks/>
        public event GetTaskInfoCompletedEventHandler GetTaskInfoCompleted;
        
        /// <remarks/>
        public event GetGraphicalStatusCompletedEventHandler GetGraphicalStatusCompleted;
        
        /// <remarks/>
        public event GetVariableListCompletedEventHandler GetVariableListCompleted;
        
        /// <remarks/>
        public event GetVariableXmlCompletedEventHandler GetVariableXmlCompleted;
        
        /// <remarks/>
        public event GetInitialVariableCompletedEventHandler GetInitialVariableCompleted;
        
        /// <remarks/>
        public event GetInitTaskIDCompletedEventHandler GetInitTaskIDCompleted;
        
        /// <remarks/>
        public event GetDomainsCompletedEventHandler GetDomainsCompleted;
        
        /// <remarks/>
        public event CheckUserCompletedEventHandler CheckUserCompleted;
        
        /// <remarks/>
        public event GetUserEntityCompletedEventHandler GetUserEntityCompleted;
        
        /// <remarks/>
        public event GetUserInfoBySearchTextCompletedEventHandler GetUserInfoBySearchTextCompleted;
        
        /// <remarks/>
        public event GetInquireListCompletedEventHandler GetInquireListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInitProcessList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProcessEntity[] GetInitProcessList(string loginName) {
            object[] results = this.Invoke("GetInitProcessList", new object[] {
                        loginName});
            return ((ProcessEntity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInitProcessListAsync(string loginName) {
            this.GetInitProcessListAsync(loginName, null);
        }
        
        /// <remarks/>
        public void GetInitProcessListAsync(string loginName, object userState) {
            if ((this.GetInitProcessListOperationCompleted == null)) {
                this.GetInitProcessListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInitProcessListOperationCompleted);
            }
            this.InvokeAsync("GetInitProcessList", new object[] {
                        loginName}, this.GetInitProcessListOperationCompleted, userState);
        }
        
        private void OnGetInitProcessListOperationCompleted(object arg) {
            if ((this.GetInitProcessListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInitProcessListCompleted(this, new GetInitProcessListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMyTaskList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TaskEntity[] GetMyTaskList(string loginName, string ProcessName) {
            object[] results = this.Invoke("GetMyTaskList", new object[] {
                        loginName,
                        ProcessName});
            return ((TaskEntity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMyTaskListAsync(string loginName, string ProcessName) {
            this.GetMyTaskListAsync(loginName, ProcessName, null);
        }
        
        /// <remarks/>
        public void GetMyTaskListAsync(string loginName, string ProcessName, object userState) {
            if ((this.GetMyTaskListOperationCompleted == null)) {
                this.GetMyTaskListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyTaskListOperationCompleted);
            }
            this.InvokeAsync("GetMyTaskList", new object[] {
                        loginName,
                        ProcessName}, this.GetMyTaskListOperationCompleted, userState);
        }
        
        private void OnGetMyTaskListOperationCompleted(object arg) {
            if ((this.GetMyTaskListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyTaskListCompleted(this, new GetMyTaskListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMyRequestList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TaskEntity[] GetMyRequestList(string loginName) {
            object[] results = this.Invoke("GetMyRequestList", new object[] {
                        loginName});
            return ((TaskEntity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMyRequestListAsync(string loginName) {
            this.GetMyRequestListAsync(loginName, null);
        }
        
        /// <remarks/>
        public void GetMyRequestListAsync(string loginName, object userState) {
            if ((this.GetMyRequestListOperationCompleted == null)) {
                this.GetMyRequestListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyRequestListOperationCompleted);
            }
            this.InvokeAsync("GetMyRequestList", new object[] {
                        loginName}, this.GetMyRequestListOperationCompleted, userState);
        }
        
        private void OnGetMyRequestListOperationCompleted(object arg) {
            if ((this.GetMyRequestListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyRequestListCompleted(this, new GetMyRequestListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMyApprovalList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TaskEntity[] GetMyApprovalList(string loginName) {
            object[] results = this.Invoke("GetMyApprovalList", new object[] {
                        loginName});
            return ((TaskEntity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMyApprovalListAsync(string loginName) {
            this.GetMyApprovalListAsync(loginName, null);
        }
        
        /// <remarks/>
        public void GetMyApprovalListAsync(string loginName, object userState) {
            if ((this.GetMyApprovalListOperationCompleted == null)) {
                this.GetMyApprovalListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyApprovalListOperationCompleted);
            }
            this.InvokeAsync("GetMyApprovalList", new object[] {
                        loginName}, this.GetMyApprovalListOperationCompleted, userState);
        }
        
        private void OnGetMyApprovalListOperationCompleted(object arg) {
            if ((this.GetMyApprovalListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyApprovalListCompleted(this, new GetMyApprovalListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubmitTask", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SubmitTask(string loginName, string taskId, string summary, System.Data.DataTable vars, string comments, string ActionType) {
            object[] results = this.Invoke("SubmitTask", new object[] {
                        loginName,
                        taskId,
                        summary,
                        vars,
                        comments,
                        ActionType});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitTaskAsync(string loginName, string taskId, string summary, System.Data.DataTable vars, string comments, string ActionType) {
            this.SubmitTaskAsync(loginName, taskId, summary, vars, comments, ActionType, null);
        }
        
        /// <remarks/>
        public void SubmitTaskAsync(string loginName, string taskId, string summary, System.Data.DataTable vars, string comments, string ActionType, object userState) {
            if ((this.SubmitTaskOperationCompleted == null)) {
                this.SubmitTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitTaskOperationCompleted);
            }
            this.InvokeAsync("SubmitTask", new object[] {
                        loginName,
                        taskId,
                        summary,
                        vars,
                        comments,
                        ActionType}, this.SubmitTaskOperationCompleted, userState);
        }
        
        private void OnSubmitTaskOperationCompleted(object arg) {
            if ((this.SubmitTaskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitTaskCompleted(this, new SubmitTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateTask", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateTask(string loginName, string taskId, string summary, System.Data.DataTable vars, string comments, string ActionType, string processName, string StepName) {
            object[] results = this.Invoke("CreateTask", new object[] {
                        loginName,
                        taskId,
                        summary,
                        vars,
                        comments,
                        ActionType,
                        processName,
                        StepName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateTaskAsync(string loginName, string taskId, string summary, System.Data.DataTable vars, string comments, string ActionType, string processName, string StepName) {
            this.CreateTaskAsync(loginName, taskId, summary, vars, comments, ActionType, processName, StepName, null);
        }
        
        /// <remarks/>
        public void CreateTaskAsync(string loginName, string taskId, string summary, System.Data.DataTable vars, string comments, string ActionType, string processName, string StepName, object userState) {
            if ((this.CreateTaskOperationCompleted == null)) {
                this.CreateTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateTaskOperationCompleted);
            }
            this.InvokeAsync("CreateTask", new object[] {
                        loginName,
                        taskId,
                        summary,
                        vars,
                        comments,
                        ActionType,
                        processName,
                        StepName}, this.CreateTaskOperationCompleted, userState);
        }
        
        private void OnCreateTaskOperationCompleted(object arg) {
            if ((this.CreateTaskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateTaskCompleted(this, new CreateTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveApprovalHistroy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SaveApprovalHistroy(int actionType, string type, string taskId, string comments, string loginName) {
            this.Invoke("SaveApprovalHistroy", new object[] {
                        actionType,
                        type,
                        taskId,
                        comments,
                        loginName});
        }
        
        /// <remarks/>
        public void SaveApprovalHistroyAsync(int actionType, string type, string taskId, string comments, string loginName) {
            this.SaveApprovalHistroyAsync(actionType, type, taskId, comments, loginName, null);
        }
        
        /// <remarks/>
        public void SaveApprovalHistroyAsync(int actionType, string type, string taskId, string comments, string loginName, object userState) {
            if ((this.SaveApprovalHistroyOperationCompleted == null)) {
                this.SaveApprovalHistroyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveApprovalHistroyOperationCompleted);
            }
            this.InvokeAsync("SaveApprovalHistroy", new object[] {
                        actionType,
                        type,
                        taskId,
                        comments,
                        loginName}, this.SaveApprovalHistroyOperationCompleted, userState);
        }
        
        private void OnSaveApprovalHistroyOperationCompleted(object arg) {
            if ((this.SaveApprovalHistroyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveApprovalHistroyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReturnTask", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReturnTask(string loginName, string taskId, string reason, string summary, System.Data.DataTable vars, string comments, string ActionType) {
            object[] results = this.Invoke("ReturnTask", new object[] {
                        loginName,
                        taskId,
                        reason,
                        summary,
                        vars,
                        comments,
                        ActionType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReturnTaskAsync(string loginName, string taskId, string reason, string summary, System.Data.DataTable vars, string comments, string ActionType) {
            this.ReturnTaskAsync(loginName, taskId, reason, summary, vars, comments, ActionType, null);
        }
        
        /// <remarks/>
        public void ReturnTaskAsync(string loginName, string taskId, string reason, string summary, System.Data.DataTable vars, string comments, string ActionType, object userState) {
            if ((this.ReturnTaskOperationCompleted == null)) {
                this.ReturnTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReturnTaskOperationCompleted);
            }
            this.InvokeAsync("ReturnTask", new object[] {
                        loginName,
                        taskId,
                        reason,
                        summary,
                        vars,
                        comments,
                        ActionType}, this.ReturnTaskOperationCompleted, userState);
        }
        
        private void OnReturnTaskOperationCompleted(object arg) {
            if ((this.ReturnTaskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReturnTaskCompleted(this, new ReturnTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RejectTask", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RejectTask(string loginName, string taskId, string reason, VarEntity[] vars) {
            object[] results = this.Invoke("RejectTask", new object[] {
                        loginName,
                        taskId,
                        reason,
                        vars});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RejectTaskAsync(string loginName, string taskId, string reason, VarEntity[] vars) {
            this.RejectTaskAsync(loginName, taskId, reason, vars, null);
        }
        
        /// <remarks/>
        public void RejectTaskAsync(string loginName, string taskId, string reason, VarEntity[] vars, object userState) {
            if ((this.RejectTaskOperationCompleted == null)) {
                this.RejectTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRejectTaskOperationCompleted);
            }
            this.InvokeAsync("RejectTask", new object[] {
                        loginName,
                        taskId,
                        reason,
                        vars}, this.RejectTaskOperationCompleted, userState);
        }
        
        private void OnRejectTaskOperationCompleted(object arg) {
            if ((this.RejectTaskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RejectTaskCompleted(this, new RejectTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTaskInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TaskEntity GetTaskInfo(string taskId) {
            object[] results = this.Invoke("GetTaskInfo", new object[] {
                        taskId});
            return ((TaskEntity)(results[0]));
        }
        
        /// <remarks/>
        public void GetTaskInfoAsync(string taskId) {
            this.GetTaskInfoAsync(taskId, null);
        }
        
        /// <remarks/>
        public void GetTaskInfoAsync(string taskId, object userState) {
            if ((this.GetTaskInfoOperationCompleted == null)) {
                this.GetTaskInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTaskInfoOperationCompleted);
            }
            this.InvokeAsync("GetTaskInfo", new object[] {
                        taskId}, this.GetTaskInfoOperationCompleted, userState);
        }
        
        private void OnGetTaskInfoOperationCompleted(object arg) {
            if ((this.GetTaskInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTaskInfoCompleted(this, new GetTaskInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGraphicalStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetGraphicalStatus(string processName, int incident) {
            object[] results = this.Invoke("GetGraphicalStatus", new object[] {
                        processName,
                        incident});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGraphicalStatusAsync(string processName, int incident) {
            this.GetGraphicalStatusAsync(processName, incident, null);
        }
        
        /// <remarks/>
        public void GetGraphicalStatusAsync(string processName, int incident, object userState) {
            if ((this.GetGraphicalStatusOperationCompleted == null)) {
                this.GetGraphicalStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGraphicalStatusOperationCompleted);
            }
            this.InvokeAsync("GetGraphicalStatus", new object[] {
                        processName,
                        incident}, this.GetGraphicalStatusOperationCompleted, userState);
        }
        
        private void OnGetGraphicalStatusOperationCompleted(object arg) {
            if ((this.GetGraphicalStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGraphicalStatusCompleted(this, new GetGraphicalStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVariableList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VarEntity[] GetVariableList(string taskID) {
            object[] results = this.Invoke("GetVariableList", new object[] {
                        taskID});
            return ((VarEntity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetVariableListAsync(string taskID) {
            this.GetVariableListAsync(taskID, null);
        }
        
        /// <remarks/>
        public void GetVariableListAsync(string taskID, object userState) {
            if ((this.GetVariableListOperationCompleted == null)) {
                this.GetVariableListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVariableListOperationCompleted);
            }
            this.InvokeAsync("GetVariableList", new object[] {
                        taskID}, this.GetVariableListOperationCompleted, userState);
        }
        
        private void OnGetVariableListOperationCompleted(object arg) {
            if ((this.GetVariableListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVariableListCompleted(this, new GetVariableListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVariableXml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetVariableXml(string processName, string taskID) {
            object[] results = this.Invoke("GetVariableXml", new object[] {
                        processName,
                        taskID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetVariableXmlAsync(string processName, string taskID) {
            this.GetVariableXmlAsync(processName, taskID, null);
        }
        
        /// <remarks/>
        public void GetVariableXmlAsync(string processName, string taskID, object userState) {
            if ((this.GetVariableXmlOperationCompleted == null)) {
                this.GetVariableXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVariableXmlOperationCompleted);
            }
            this.InvokeAsync("GetVariableXml", new object[] {
                        processName,
                        taskID}, this.GetVariableXmlOperationCompleted, userState);
        }
        
        private void OnGetVariableXmlOperationCompleted(object arg) {
            if ((this.GetVariableXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVariableXmlCompleted(this, new GetVariableXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInitialVariable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetInitialVariable(string processName) {
            object[] results = this.Invoke("GetInitialVariable", new object[] {
                        processName});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInitialVariableAsync(string processName) {
            this.GetInitialVariableAsync(processName, null);
        }
        
        /// <remarks/>
        public void GetInitialVariableAsync(string processName, object userState) {
            if ((this.GetInitialVariableOperationCompleted == null)) {
                this.GetInitialVariableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInitialVariableOperationCompleted);
            }
            this.InvokeAsync("GetInitialVariable", new object[] {
                        processName}, this.GetInitialVariableOperationCompleted, userState);
        }
        
        private void OnGetInitialVariableOperationCompleted(object arg) {
            if ((this.GetInitialVariableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInitialVariableCompleted(this, new GetInitialVariableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInitTaskID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetInitTaskID(string processName) {
            object[] results = this.Invoke("GetInitTaskID", new object[] {
                        processName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetInitTaskIDAsync(string processName) {
            this.GetInitTaskIDAsync(processName, null);
        }
        
        /// <remarks/>
        public void GetInitTaskIDAsync(string processName, object userState) {
            if ((this.GetInitTaskIDOperationCompleted == null)) {
                this.GetInitTaskIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInitTaskIDOperationCompleted);
            }
            this.InvokeAsync("GetInitTaskID", new object[] {
                        processName}, this.GetInitTaskIDOperationCompleted, userState);
        }
        
        private void OnGetInitTaskIDOperationCompleted(object arg) {
            if ((this.GetInitTaskIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInitTaskIDCompleted(this, new GetInitTaskIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDomains", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetDomains() {
            object[] results = this.Invoke("GetDomains", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDomainsAsync() {
            this.GetDomainsAsync(null);
        }
        
        /// <remarks/>
        public void GetDomainsAsync(object userState) {
            if ((this.GetDomainsOperationCompleted == null)) {
                this.GetDomainsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDomainsOperationCompleted);
            }
            this.InvokeAsync("GetDomains", new object[0], this.GetDomainsOperationCompleted, userState);
        }
        
        private void OnGetDomainsOperationCompleted(object arg) {
            if ((this.GetDomainsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDomainsCompleted(this, new GetDomainsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckUser(string loginName, string password) {
            object[] results = this.Invoke("CheckUser", new object[] {
                        loginName,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckUserAsync(string loginName, string password) {
            this.CheckUserAsync(loginName, password, null);
        }
        
        /// <remarks/>
        public void CheckUserAsync(string loginName, string password, object userState) {
            if ((this.CheckUserOperationCompleted == null)) {
                this.CheckUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckUserOperationCompleted);
            }
            this.InvokeAsync("CheckUser", new object[] {
                        loginName,
                        password}, this.CheckUserOperationCompleted, userState);
        }
        
        private void OnCheckUserOperationCompleted(object arg) {
            if ((this.CheckUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckUserCompleted(this, new CheckUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserEntity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserEntity GetUserEntity(string loginName) {
            object[] results = this.Invoke("GetUserEntity", new object[] {
                        loginName});
            return ((UserEntity)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserEntityAsync(string loginName) {
            this.GetUserEntityAsync(loginName, null);
        }
        
        /// <remarks/>
        public void GetUserEntityAsync(string loginName, object userState) {
            if ((this.GetUserEntityOperationCompleted == null)) {
                this.GetUserEntityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserEntityOperationCompleted);
            }
            this.InvokeAsync("GetUserEntity", new object[] {
                        loginName}, this.GetUserEntityOperationCompleted, userState);
        }
        
        private void OnGetUserEntityOperationCompleted(object arg) {
            if ((this.GetUserEntityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserEntityCompleted(this, new GetUserEntityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInfoBySearchText", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserEntity[] GetUserInfoBySearchText(string searchText) {
            object[] results = this.Invoke("GetUserInfoBySearchText", new object[] {
                        searchText});
            return ((UserEntity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoBySearchTextAsync(string searchText) {
            this.GetUserInfoBySearchTextAsync(searchText, null);
        }
        
        /// <remarks/>
        public void GetUserInfoBySearchTextAsync(string searchText, object userState) {
            if ((this.GetUserInfoBySearchTextOperationCompleted == null)) {
                this.GetUserInfoBySearchTextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoBySearchTextOperationCompleted);
            }
            this.InvokeAsync("GetUserInfoBySearchText", new object[] {
                        searchText}, this.GetUserInfoBySearchTextOperationCompleted, userState);
        }
        
        private void OnGetUserInfoBySearchTextOperationCompleted(object arg) {
            if ((this.GetUserInfoBySearchTextCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoBySearchTextCompleted(this, new GetUserInfoBySearchTextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInquireList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserEntity[] GetInquireList(string ProcessName, string IncidentID) {
            object[] results = this.Invoke("GetInquireList", new object[] {
                        ProcessName,
                        IncidentID});
            return ((UserEntity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInquireListAsync(string ProcessName, string IncidentID) {
            this.GetInquireListAsync(ProcessName, IncidentID, null);
        }
        
        /// <remarks/>
        public void GetInquireListAsync(string ProcessName, string IncidentID, object userState) {
            if ((this.GetInquireListOperationCompleted == null)) {
                this.GetInquireListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInquireListOperationCompleted);
            }
            this.InvokeAsync("GetInquireList", new object[] {
                        ProcessName,
                        IncidentID}, this.GetInquireListOperationCompleted, userState);
        }
        
        private void OnGetInquireListOperationCompleted(object arg) {
            if ((this.GetInquireListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInquireListCompleted(this, new GetInquireListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessEntity {
        
        private string pROCESSNAMEField;
        
        private string cATEGORYNAMEField;
        
        private int iNITIATORTYPEField;
        
        private string iNITIATEIDField;
        
        private string iCONField;
        
        private string rECIPIENTField;
        
        private int idField;
        
        private int oRDERNOField;
        
        private string cATEGORYENNAMEField;
        
        private string pROCESSENNAMEField;
        
        private int pROCESSNOField;
        
        private string serviceNameField;
        
        /// <remarks/>
        public string PROCESSNAME {
            get {
                return this.pROCESSNAMEField;
            }
            set {
                this.pROCESSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string CATEGORYNAME {
            get {
                return this.cATEGORYNAMEField;
            }
            set {
                this.cATEGORYNAMEField = value;
            }
        }
        
        /// <remarks/>
        public int INITIATORTYPE {
            get {
                return this.iNITIATORTYPEField;
            }
            set {
                this.iNITIATORTYPEField = value;
            }
        }
        
        /// <remarks/>
        public string INITIATEID {
            get {
                return this.iNITIATEIDField;
            }
            set {
                this.iNITIATEIDField = value;
            }
        }
        
        /// <remarks/>
        public string ICON {
            get {
                return this.iCONField;
            }
            set {
                this.iCONField = value;
            }
        }
        
        /// <remarks/>
        public string RECIPIENT {
            get {
                return this.rECIPIENTField;
            }
            set {
                this.rECIPIENTField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ORDERNO {
            get {
                return this.oRDERNOField;
            }
            set {
                this.oRDERNOField = value;
            }
        }
        
        /// <remarks/>
        public string CATEGORYENNAME {
            get {
                return this.cATEGORYENNAMEField;
            }
            set {
                this.cATEGORYENNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string PROCESSENNAME {
            get {
                return this.pROCESSENNAMEField;
            }
            set {
                this.pROCESSENNAMEField = value;
            }
        }
        
        /// <remarks/>
        public int PROCESSNO {
            get {
                return this.pROCESSNOField;
            }
            set {
                this.pROCESSNOField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserEntity {
        
        private int uSERIDField;
        
        private string lOGINNAMEField;
        
        private string uSERNAMEField;
        
        private string uSERCODEField;
        
        private string eMAILField;
        
        private string mOBILENOField;
        
        private string tELField;
        
        private string imField;
        
        private string pASSWORDField;
        
        private string lANGUAGEField;
        
        private string pICTUREField;
        
        private System.Nullable<int> oRDERNOField;
        
        private System.Nullable<System.DateTime> cREATEDATEField;
        
        private string cREATEBYField;
        
        private System.Nullable<System.DateTime> uPDATEDATEField;
        
        private string uPDATEBYField;
        
        private string iSACTIVEField;
        
        private string eXT01Field;
        
        private string eXT02Field;
        
        private string eXT03Field;
        
        private string eXT04Field;
        
        private string eXT05Field;
        
        private string eXT06Field;
        
        private string eXT07Field;
        
        private string eXT08Field;
        
        private string eXT09Field;
        
        private string eXT10Field;
        
        private string eXT11Field;
        
        private string eXT12Field;
        
        private string eXT13Field;
        
        private string eXT14Field;
        
        private string eXT15Field;
        
        private string eXT16Field;
        
        private string eXT17Field;
        
        private string eXT18Field;
        
        private string eXT19Field;
        
        private string eXT20Field;
        
        private string eXT21Field;
        
        private string eXT22Field;
        
        private string eXT23Field;
        
        private string eXT24Field;
        
        private string eXT25Field;
        
        private string eXT26Field;
        
        private string eXT27Field;
        
        private string eXT28Field;
        
        private string eXT29Field;
        
        private string eXT30Field;
        
        private string startWorkDateField;
        
        private string entryDateField;
        
        private string jOBFUNCTIONField;
        
        private string dEPARTMENTField;
        
        private string dIRECTREPORTNAMEField;
        
        private int sUPERVISORUSERIDField;
        
        /// <remarks/>
        public int USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
            }
        }
        
        /// <remarks/>
        public string LOGINNAME {
            get {
                return this.lOGINNAMEField;
            }
            set {
                this.lOGINNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string USERNAME {
            get {
                return this.uSERNAMEField;
            }
            set {
                this.uSERNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string USERCODE {
            get {
                return this.uSERCODEField;
            }
            set {
                this.uSERCODEField = value;
            }
        }
        
        /// <remarks/>
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        public string MOBILENO {
            get {
                return this.mOBILENOField;
            }
            set {
                this.mOBILENOField = value;
            }
        }
        
        /// <remarks/>
        public string TEL {
            get {
                return this.tELField;
            }
            set {
                this.tELField = value;
            }
        }
        
        /// <remarks/>
        public string IM {
            get {
                return this.imField;
            }
            set {
                this.imField = value;
            }
        }
        
        /// <remarks/>
        public string PASSWORD {
            get {
                return this.pASSWORDField;
            }
            set {
                this.pASSWORDField = value;
            }
        }
        
        /// <remarks/>
        public string LANGUAGE {
            get {
                return this.lANGUAGEField;
            }
            set {
                this.lANGUAGEField = value;
            }
        }
        
        /// <remarks/>
        public string PICTURE {
            get {
                return this.pICTUREField;
            }
            set {
                this.pICTUREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ORDERNO {
            get {
                return this.oRDERNOField;
            }
            set {
                this.oRDERNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CREATEDATE {
            get {
                return this.cREATEDATEField;
            }
            set {
                this.cREATEDATEField = value;
            }
        }
        
        /// <remarks/>
        public string CREATEBY {
            get {
                return this.cREATEBYField;
            }
            set {
                this.cREATEBYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> UPDATEDATE {
            get {
                return this.uPDATEDATEField;
            }
            set {
                this.uPDATEDATEField = value;
            }
        }
        
        /// <remarks/>
        public string UPDATEBY {
            get {
                return this.uPDATEBYField;
            }
            set {
                this.uPDATEBYField = value;
            }
        }
        
        /// <remarks/>
        public string ISACTIVE {
            get {
                return this.iSACTIVEField;
            }
            set {
                this.iSACTIVEField = value;
            }
        }
        
        /// <remarks/>
        public string EXT01 {
            get {
                return this.eXT01Field;
            }
            set {
                this.eXT01Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT02 {
            get {
                return this.eXT02Field;
            }
            set {
                this.eXT02Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT03 {
            get {
                return this.eXT03Field;
            }
            set {
                this.eXT03Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT04 {
            get {
                return this.eXT04Field;
            }
            set {
                this.eXT04Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT05 {
            get {
                return this.eXT05Field;
            }
            set {
                this.eXT05Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT06 {
            get {
                return this.eXT06Field;
            }
            set {
                this.eXT06Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT07 {
            get {
                return this.eXT07Field;
            }
            set {
                this.eXT07Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT08 {
            get {
                return this.eXT08Field;
            }
            set {
                this.eXT08Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT09 {
            get {
                return this.eXT09Field;
            }
            set {
                this.eXT09Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT10 {
            get {
                return this.eXT10Field;
            }
            set {
                this.eXT10Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT11 {
            get {
                return this.eXT11Field;
            }
            set {
                this.eXT11Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT12 {
            get {
                return this.eXT12Field;
            }
            set {
                this.eXT12Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT13 {
            get {
                return this.eXT13Field;
            }
            set {
                this.eXT13Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT14 {
            get {
                return this.eXT14Field;
            }
            set {
                this.eXT14Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT15 {
            get {
                return this.eXT15Field;
            }
            set {
                this.eXT15Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT16 {
            get {
                return this.eXT16Field;
            }
            set {
                this.eXT16Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT17 {
            get {
                return this.eXT17Field;
            }
            set {
                this.eXT17Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT18 {
            get {
                return this.eXT18Field;
            }
            set {
                this.eXT18Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT19 {
            get {
                return this.eXT19Field;
            }
            set {
                this.eXT19Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT20 {
            get {
                return this.eXT20Field;
            }
            set {
                this.eXT20Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT21 {
            get {
                return this.eXT21Field;
            }
            set {
                this.eXT21Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT22 {
            get {
                return this.eXT22Field;
            }
            set {
                this.eXT22Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT23 {
            get {
                return this.eXT23Field;
            }
            set {
                this.eXT23Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT24 {
            get {
                return this.eXT24Field;
            }
            set {
                this.eXT24Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT25 {
            get {
                return this.eXT25Field;
            }
            set {
                this.eXT25Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT26 {
            get {
                return this.eXT26Field;
            }
            set {
                this.eXT26Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT27 {
            get {
                return this.eXT27Field;
            }
            set {
                this.eXT27Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT28 {
            get {
                return this.eXT28Field;
            }
            set {
                this.eXT28Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT29 {
            get {
                return this.eXT29Field;
            }
            set {
                this.eXT29Field = value;
            }
        }
        
        /// <remarks/>
        public string EXT30 {
            get {
                return this.eXT30Field;
            }
            set {
                this.eXT30Field = value;
            }
        }
        
        /// <remarks/>
        public string StartWorkDate {
            get {
                return this.startWorkDateField;
            }
            set {
                this.startWorkDateField = value;
            }
        }
        
        /// <remarks/>
        public string EntryDate {
            get {
                return this.entryDateField;
            }
            set {
                this.entryDateField = value;
            }
        }
        
        /// <remarks/>
        public string JOBFUNCTION {
            get {
                return this.jOBFUNCTIONField;
            }
            set {
                this.jOBFUNCTIONField = value;
            }
        }
        
        /// <remarks/>
        public string DEPARTMENT {
            get {
                return this.dEPARTMENTField;
            }
            set {
                this.dEPARTMENTField = value;
            }
        }
        
        /// <remarks/>
        public string DIRECTREPORTNAME {
            get {
                return this.dIRECTREPORTNAMEField;
            }
            set {
                this.dIRECTREPORTNAMEField = value;
            }
        }
        
        /// <remarks/>
        public int SUPERVISORUSERID {
            get {
                return this.sUPERVISORUSERIDField;
            }
            set {
                this.sUPERVISORUSERIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VarEntity {
        
        private string nameField;
        
        private string valueField;
        
        private bool nillableField;
        
        private string descriptionField;
        
        private string typeField;
        
        private string complexTypeField;
        
        private string parentNameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public bool Nillable {
            get {
                return this.nillableField;
            }
            set {
                this.nillableField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string ComplexType {
            get {
                return this.complexTypeField;
            }
            set {
                this.complexTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ParentName {
            get {
                return this.parentNameField;
            }
            set {
                this.parentNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TaskEntity {
        
        private string _ICONField;
        
        private string tASKIDField;
        
        private string pROCESSNAMEField;
        
        private int iNCIDENTField;
        
        private string sUMMARYField;
        
        private string sourceTaskIDField;
        
        private string displaySummaryField;
        
        private string hELPURLField;
        
        private string sTEPLABELField;
        
        private bool sYNCField;
        
        private string sTEPIDField;
        
        private int sTATUSField;
        
        private int pROCESSSTATUSField;
        
        private int sUBSTATUSField;
        
        private System.DateTime sTARTTIMEField;
        
        private System.DateTime eNDTIMEField;
        
        private System.DateTime oVERDUETIMEField;
        
        private string tASKUSERField;
        
        private string aSSIGNEDTOUSERField;
        
        private string iNITIATORField;
        
        private string aPLICANTField;
        
        private string dEPARTMENTField;
        
        private string sERVERNAMEField;
        
        private string sERVERTASKIDField;
        
        private string fORMURLField;
        
        private string eRRORMESSAGEField;
        
        private VarEntity[] varListField;
        
        private string rEASONField;
        
        private string cOMMENTSField;
        
        private string tYPEField;
        
        private string requestorDateField;
        
        private string iCONField;
        
        /// <remarks/>
        public string _ICON {
            get {
                return this._ICONField;
            }
            set {
                this._ICONField = value;
            }
        }
        
        /// <remarks/>
        public string TASKID {
            get {
                return this.tASKIDField;
            }
            set {
                this.tASKIDField = value;
            }
        }
        
        /// <remarks/>
        public string PROCESSNAME {
            get {
                return this.pROCESSNAMEField;
            }
            set {
                this.pROCESSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public int INCIDENT {
            get {
                return this.iNCIDENTField;
            }
            set {
                this.iNCIDENTField = value;
            }
        }
        
        /// <remarks/>
        public string SUMMARY {
            get {
                return this.sUMMARYField;
            }
            set {
                this.sUMMARYField = value;
            }
        }
        
        /// <remarks/>
        public string SourceTaskID {
            get {
                return this.sourceTaskIDField;
            }
            set {
                this.sourceTaskIDField = value;
            }
        }
        
        /// <remarks/>
        public string DisplaySummary {
            get {
                return this.displaySummaryField;
            }
            set {
                this.displaySummaryField = value;
            }
        }
        
        /// <remarks/>
        public string HELPURL {
            get {
                return this.hELPURLField;
            }
            set {
                this.hELPURLField = value;
            }
        }
        
        /// <remarks/>
        public string STEPLABEL {
            get {
                return this.sTEPLABELField;
            }
            set {
                this.sTEPLABELField = value;
            }
        }
        
        /// <remarks/>
        public bool SYNC {
            get {
                return this.sYNCField;
            }
            set {
                this.sYNCField = value;
            }
        }
        
        /// <remarks/>
        public string STEPID {
            get {
                return this.sTEPIDField;
            }
            set {
                this.sTEPIDField = value;
            }
        }
        
        /// <remarks/>
        public int STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        public int PROCESSSTATUS {
            get {
                return this.pROCESSSTATUSField;
            }
            set {
                this.pROCESSSTATUSField = value;
            }
        }
        
        /// <remarks/>
        public int SUBSTATUS {
            get {
                return this.sUBSTATUSField;
            }
            set {
                this.sUBSTATUSField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime STARTTIME {
            get {
                return this.sTARTTIMEField;
            }
            set {
                this.sTARTTIMEField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ENDTIME {
            get {
                return this.eNDTIMEField;
            }
            set {
                this.eNDTIMEField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OVERDUETIME {
            get {
                return this.oVERDUETIMEField;
            }
            set {
                this.oVERDUETIMEField = value;
            }
        }
        
        /// <remarks/>
        public string TASKUSER {
            get {
                return this.tASKUSERField;
            }
            set {
                this.tASKUSERField = value;
            }
        }
        
        /// <remarks/>
        public string ASSIGNEDTOUSER {
            get {
                return this.aSSIGNEDTOUSERField;
            }
            set {
                this.aSSIGNEDTOUSERField = value;
            }
        }
        
        /// <remarks/>
        public string INITIATOR {
            get {
                return this.iNITIATORField;
            }
            set {
                this.iNITIATORField = value;
            }
        }
        
        /// <remarks/>
        public string APLICANT {
            get {
                return this.aPLICANTField;
            }
            set {
                this.aPLICANTField = value;
            }
        }
        
        /// <remarks/>
        public string DEPARTMENT {
            get {
                return this.dEPARTMENTField;
            }
            set {
                this.dEPARTMENTField = value;
            }
        }
        
        /// <remarks/>
        public string SERVERNAME {
            get {
                return this.sERVERNAMEField;
            }
            set {
                this.sERVERNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string SERVERTASKID {
            get {
                return this.sERVERTASKIDField;
            }
            set {
                this.sERVERTASKIDField = value;
            }
        }
        
        /// <remarks/>
        public string FORMURL {
            get {
                return this.fORMURLField;
            }
            set {
                this.fORMURLField = value;
            }
        }
        
        /// <remarks/>
        public string ERRORMESSAGE {
            get {
                return this.eRRORMESSAGEField;
            }
            set {
                this.eRRORMESSAGEField = value;
            }
        }
        
        /// <remarks/>
        public VarEntity[] VarList {
            get {
                return this.varListField;
            }
            set {
                this.varListField = value;
            }
        }
        
        /// <remarks/>
        public string REASON {
            get {
                return this.rEASONField;
            }
            set {
                this.rEASONField = value;
            }
        }
        
        /// <remarks/>
        public string COMMENTS {
            get {
                return this.cOMMENTSField;
            }
            set {
                this.cOMMENTSField = value;
            }
        }
        
        /// <remarks/>
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        public string RequestorDate {
            get {
                return this.requestorDateField;
            }
            set {
                this.requestorDateField = value;
            }
        }
        
        /// <remarks/>
        public string ICON {
            get {
                return this.iCONField;
            }
            set {
                this.iCONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetInitProcessListCompletedEventHandler(object sender, GetInitProcessListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInitProcessListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInitProcessListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProcessEntity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProcessEntity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetMyTaskListCompletedEventHandler(object sender, GetMyTaskListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyTaskListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyTaskListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaskEntity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaskEntity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetMyRequestListCompletedEventHandler(object sender, GetMyRequestListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyRequestListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyRequestListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaskEntity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaskEntity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetMyApprovalListCompletedEventHandler(object sender, GetMyApprovalListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyApprovalListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyApprovalListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaskEntity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaskEntity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SubmitTaskCompletedEventHandler(object sender, SubmitTaskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CreateTaskCompletedEventHandler(object sender, CreateTaskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SaveApprovalHistroyCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReturnTaskCompletedEventHandler(object sender, ReturnTaskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReturnTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReturnTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RejectTaskCompletedEventHandler(object sender, RejectTaskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RejectTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RejectTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetTaskInfoCompletedEventHandler(object sender, GetTaskInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTaskInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTaskInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaskEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaskEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetGraphicalStatusCompletedEventHandler(object sender, GetGraphicalStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGraphicalStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGraphicalStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetVariableListCompletedEventHandler(object sender, GetVariableListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVariableListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVariableListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VarEntity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VarEntity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetVariableXmlCompletedEventHandler(object sender, GetVariableXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVariableXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVariableXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetInitialVariableCompletedEventHandler(object sender, GetInitialVariableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInitialVariableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInitialVariableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetInitTaskIDCompletedEventHandler(object sender, GetInitTaskIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInitTaskIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInitTaskIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDomainsCompletedEventHandler(object sender, GetDomainsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDomainsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDomainsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CheckUserCompletedEventHandler(object sender, CheckUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetUserEntityCompletedEventHandler(object sender, GetUserEntityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserEntityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserEntityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetUserInfoBySearchTextCompletedEventHandler(object sender, GetUserInfoBySearchTextCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoBySearchTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoBySearchTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserEntity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserEntity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetInquireListCompletedEventHandler(object sender, GetInquireListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInquireListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInquireListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserEntity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserEntity[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591