//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.1。
// 
namespace UWF.WebServiceProxy {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddSSOUserTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserAccountByTicketOperationCompleted;
        
        /// <remarks/>
        public Service() {
            this.Url = "http://localhost:7922/Service.asmx";
        }
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        public event AddSSOUserTicketCompletedEventHandler AddSSOUserTicketCompleted;
        
        /// <remarks/>
        public event GetUserAccountByTicketCompletedEventHandler GetUserAccountByTicketCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ping", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RepResult Ping() {
            object[] results = this.Invoke("Ping", new object[0]);
            return ((RepResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPing(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Ping", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public RepResult EndPing(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RepResult)(results[0]));
        }
        
        /// <remarks/>
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        /// <remarks/>
        public void PingAsync(object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[0], this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddSSOUserTicket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RepResult AddSSOUserTicket(ReqUserTicket ticketModel) {
            object[] results = this.Invoke("AddSSOUserTicket", new object[] {
                        ticketModel});
            return ((RepResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddSSOUserTicket(ReqUserTicket ticketModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddSSOUserTicket", new object[] {
                        ticketModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public RepResult EndAddSSOUserTicket(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RepResult)(results[0]));
        }
        
        /// <remarks/>
        public void AddSSOUserTicketAsync(ReqUserTicket ticketModel) {
            this.AddSSOUserTicketAsync(ticketModel, null);
        }
        
        /// <remarks/>
        public void AddSSOUserTicketAsync(ReqUserTicket ticketModel, object userState) {
            if ((this.AddSSOUserTicketOperationCompleted == null)) {
                this.AddSSOUserTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddSSOUserTicketOperationCompleted);
            }
            this.InvokeAsync("AddSSOUserTicket", new object[] {
                        ticketModel}, this.AddSSOUserTicketOperationCompleted, userState);
        }
        
        private void OnAddSSOUserTicketOperationCompleted(object arg) {
            if ((this.AddSSOUserTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddSSOUserTicketCompleted(this, new AddSSOUserTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserAccountByTicket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RepResultOfString GetUserAccountByTicket(string ticket) {
            object[] results = this.Invoke("GetUserAccountByTicket", new object[] {
                        ticket});
            return ((RepResultOfString)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUserAccountByTicket(string ticket, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUserAccountByTicket", new object[] {
                        ticket}, callback, asyncState);
        }
        
        /// <remarks/>
        public RepResultOfString EndGetUserAccountByTicket(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RepResultOfString)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserAccountByTicketAsync(string ticket) {
            this.GetUserAccountByTicketAsync(ticket, null);
        }
        
        /// <remarks/>
        public void GetUserAccountByTicketAsync(string ticket, object userState) {
            if ((this.GetUserAccountByTicketOperationCompleted == null)) {
                this.GetUserAccountByTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserAccountByTicketOperationCompleted);
            }
            this.InvokeAsync("GetUserAccountByTicket", new object[] {
                        ticket}, this.GetUserAccountByTicketOperationCompleted, userState);
        }
        
        private void OnGetUserAccountByTicketOperationCompleted(object arg) {
            if ((this.GetUserAccountByTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserAccountByTicketCompleted(this, new GetUserAccountByTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RepResultOfString))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RepResult {
        
        private int codeField;
        
        private string msgField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReqUserTicket {
        
        private string ticketField;
        
        private string userAccountField;
        
        private System.DateTime expiredDateField;
        
        /// <remarks/>
        public string Ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
            }
        }
        
        /// <remarks/>
        public string UserAccount {
            get {
                return this.userAccountField;
            }
            set {
                this.userAccountField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiredDate {
            get {
                return this.expiredDateField;
            }
            set {
                this.expiredDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RepResultOfString : RepResult {
        
        private string dataField;
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RepResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RepResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void AddSSOUserTicketCompletedEventHandler(object sender, AddSSOUserTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddSSOUserTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddSSOUserTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RepResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RepResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetUserAccountByTicketCompletedEventHandler(object sender, GetUserAccountByTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserAccountByTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserAccountByTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RepResultOfString Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RepResultOfString)(this.results[0]));
            }
        }
    }
}
